services:
  backend:
    image: gaggu221/recipe-store_backend
    links:
      - db
    ports:
      - "5000:5000"  
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    image: gaggu221/recipe-store-frontend
    depends_on:
      - backend
      - db
    ports:
      - "80:80"
    restart: always
