LOAD DATA INFILE '/var/lib/mysql-files/Recipe.csv'
INTO TABLE mydb.RECIPE
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(RECIPE_ID, RECIPE_NAME, PREP_TIME, COOK_TIME, TOTAL_TIME, SERVINGS, CUISINE, COURSE, DIET, INSTRUCTIONS);