LOAD DATA INFILE '/var/lib/mysql-files/RecipeIngredients.csv'
INTO TABLE mydb.RECIPE_INGREDIENTS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(RECIPE_INGREDENT_ID, RECIPE_ID, INGREDIENT_ID);