-- MySQL Script generated by MySQL Workbench
-- Fri Mar  4 11:58:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`INGREDIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INGREDIENT` (
  `INGREDIENT_ID` INT NOT NULL AUTO_INCREMENT,
  `INGREDIENT_NAME` VARCHAR(128) NULL,
  PRIMARY KEY (`INGREDIENT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RECIPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RECIPE` (
  `RECIPE_ID` INT NOT NULL,
  `RECIPE_NAME` VARCHAR(45) NULL,
  `PREP_TIME` INT NULL DEFAULT 0,
  `COOK_TIME` INT NULL DEFAULT 0,
  `TOTAL_TIME` int DEFAULT NULL,
  `SERVINGS` int DEFAULT NULL,
  `CUISINE` varchar(50) DEFAULT NULL,
  `COURSE` varchar(50) DEFAULT NULL,
  `DIET` varchar(50) DEFAULT NULL,
  `INSTRUCTIONS` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`RECIPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RECIPE_INTEGRATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RECIPE_INGREDIENTS` (
  `RECIPE_INGREDENT_ID` INT NOT NULL AUTO_INCREMENT,
  `RECIPE_ID` INT NOT NULL,
  `INGREDIENT_ID` INT NOT NULL,
  PRIMARY KEY (`RECIPE_INGREDENT_ID`),
  INDEX `RECIPE_ID_idx` (`RECIPE_ID` ASC) VISIBLE,
  INDEX `INGREDIENT_ID_idx` (`INGREDIENT_ID` ASC) VISIBLE,
  CONSTRAINT `RECIPE_ID`
    FOREIGN KEY (`RECIPE_ID`)
    REFERENCES `mydb`.`RECIPE` (`RECIPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `INGREDIENT_ID`
    FOREIGN KEY (`INGREDIENT_ID`)
    REFERENCES `mydb`.`INGREDIENT` (`INGREDIENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
